### ISSUE TITLE
。

### ISSUE THREAD

**Issue by crimson-gao** [sun-lingyu/MIT6.824-spring21#1]

**Comment by OrientationJump** [comment]
![image](https://user-images.githubusercontent.com/39024757/116780840-93c49780-aab1-11eb-9c45-fd7893ddd9ae.png)
另外在receiver的下半部分最好也注意下

**Comment by OrientationJump** [comment]
发送installSnapshot给lastApplied比较小的follower，因为service的安装机制，导致其只安装了最后一个index，中间的部分会丢失。
所以除非有必要，不然不应该随便发送installSnapshot，所以要慎重对待nextIndex
